import type { Category, PrayerDay, TaskTemplate, TimeBlock } from "./types"

export const seedCategories: Category[] = [
  {
    id: "prayer",
    nameAr: "صلاة",
    icon: "mosque",
    color: "emerald",
    defaultDurationMinutes: 20,
    defaultPriority: "high",
  },
  {
    id: "worship",
    nameAr: "عبادة",
    icon: "sparkles",
    color: "teal",
    defaultDurationMinutes: 25,
    defaultPriority: "high",
  },
  {
    id: "family",
    nameAr: "العائلة",
    icon: "home",
    color: "amber",
    defaultDurationMinutes: 45,
    defaultPriority: "medium",
  },
  {
    id: "health",
    nameAr: "الصحة",
    icon: "activity",
    color: "sky",
    defaultDurationMinutes: 45,
    defaultPriority: "medium",
  },
  {
    id: "study",
    nameAr: "تعلم",
    icon: "book",
    color: "violet",
    defaultDurationMinutes: 50,
    defaultPriority: "medium",
  },
]

export const seedTimeBlocks: TimeBlock[] = [
  {
    id: "last_sixth_to_fajr",
    nameAr: "السدس / قبل الفجر",
    sortOrder: 10,
    color: "indigo",
    startSource: "fixed",
    fixedStart: "03:20",
    endSource: "Fajr",
  },
  {
    id: "fajr_to_sunrise",
    nameAr: "الفجر إلى الشروق",
    sortOrder: 20,
    color: "emerald",
    startSource: "Fajr",
    endSource: "Sunrise",
  },
  {
    id: "sunrise_to_dhuhr",
    nameAr: "الشروق إلى الظهر",
    sortOrder: 30,
    color: "sky",
    startSource: "Sunrise",
    endSource: "Dhuhr",
  },
  {
    id: "dhuhr_to_asr",
    nameAr: "الظهر إلى العصر",
    sortOrder: 40,
    color: "amber",
    startSource: "Dhuhr",
    endSource: "Asr",
  },
  {
    id: "asr_to_maghrib",
    nameAr: "العصر إلى المغرب",
    sortOrder: 50,
    color: "orange",
    startSource: "Asr",
    endSource: "Maghrib",
  },
  {
    id: "maghrib_to_isha",
    nameAr: "المغرب إلى العشاء",
    sortOrder: 60,
    color: "rose",
    startSource: "Maghrib",
    endSource: "Isha",
  },
  {
    id: "isha_to_sleep",
    nameAr: "العشاء إلى النوم / السدس",
    sortOrder: 70,
    color: "slate",
    startSource: "Isha",
    endSource: "fixed",
    fixedEnd: "23:30",
  },
]

export const seedTaskTemplates: TaskTemplate[] = [
  {
    id: "qiyam",
    title: "قيام",
    categoryId: "worship",
    defaultTimeBlockId: "last_sixth_to_fajr",
    defaultDurationMinutes: 25,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    repeatInterval: 1,
    startDate: "2026-05-24",
    notes: "",
    checklist: [],
    color: "indigo",
    isActive: true,
    includeInCalendar: true,
    sortOrder: 10,
  },
  {
    id: "suhoor",
    title: "سحور + استغفار",
    categoryId: "worship",
    defaultTimeBlockId: "last_sixth_to_fajr",
    defaultDurationMinutes: 30,
    defaultPriority: "high",
    repeatType: "selected_days",
    repeatDays: [1, 4],
    repeatInterval: 1,
    startDate: "2026-05-24",
    notes: "مخصص للإثنين والخميس",
    checklist: ["استغفار"],
    color: "teal",
    isActive: true,
    includeInCalendar: true,
    sortOrder: 20,
  },
  {
    id: "fajr",
    title: "صلاة الفجر",
    categoryId: "prayer",
    defaultTimeBlockId: "fajr_to_sunrise",
    defaultDurationMinutes: 20,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    repeatInterval: 1,
    startDate: "2026-05-24",
    notes: "قبل الصلاة وبعدها",
    checklist: ["ترديد الأذان", "أذكار الصلاة", "أذكار الصباح"],
    color: "emerald",
    isActive: true,
    includeInCalendar: true,
    sortOrder: 10,
  },
  {
    id: "exercise",
    title: "رياضة",
    categoryId: "health",
    defaultTimeBlockId: "sunrise_to_dhuhr",
    defaultDurationMinutes: 45,
    defaultPriority: "medium",
    repeatType: "selected_days",
    repeatDays: [0, 2, 4],
    repeatInterval: 1,
    startDate: "2026-05-24",
    notes: "",
    checklist: ["مقاومة / جري"],
    color: "sky",
    isActive: true,
    includeInCalendar: true,
    sortOrder: 20,
  },
  {
    id: "dhuhr",
    title: "صلاة الظهر",
    categoryId: "prayer",
    defaultTimeBlockId: "dhuhr_to_asr",
    defaultDurationMinutes: 20,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    repeatInterval: 1,
    startDate: "2026-05-24",
    notes: "",
    checklist: ["ترديد الأذان", "أذكار الصلاة"],
    color: "amber",
    isActive: true,
    includeInCalendar: true,
    sortOrder: 10,
  },
  {
    id: "maghrib",
    title: "صلاة المغرب",
    categoryId: "prayer",
    defaultTimeBlockId: "maghrib_to_isha",
    defaultDurationMinutes: 20,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    repeatInterval: 1,
    startDate: "2026-05-24",
    notes: "",
    checklist: ["ترديد الأذان", "أذكار الصلاة", "أذكار المساء"],
    color: "rose",
    isActive: true,
    includeInCalendar: true,
    sortOrder: 10,
  },
  {
    id: "family-dinner",
    title: "عشاء مع العائلة",
    categoryId: "family",
    defaultTimeBlockId: "isha_to_sleep",
    defaultDurationMinutes: 45,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    repeatInterval: 1,
    startDate: "2026-05-24",
    notes: "",
    checklist: [],
    color: "amber",
    isActive: true,
    includeInCalendar: true,
    sortOrder: 20,
  },
]

export const seedPrayerDays: PrayerDay[] = [
  "2026-05-24",
  "2026-05-25",
  "2026-05-26",
  "2026-05-27",
  "2026-05-28",
  "2026-05-29",
  "2026-05-30",
].map((date, index) => ({
  date,
  timezone: "Asia/Riyadh",
  timings: {
    Fajr: `04:${String(12 + index).padStart(2, "0")}`,
    Sunrise: `05:${String(37 + index).padStart(2, "0")}`,
    Dhuhr: "11:54",
    Asr: "15:15",
    Maghrib: "18:38",
    Isha: "20:08",
  },
}))
