import type { Category, PrayerDay, TaskTemplate, TimeBlock } from "./types"

export const seedCategories: Category[] = [
  {
    id: "prayer",
    nameAr: "صلاة",
    icon: "mosque",
    color: "emerald",
    defaultDurationMinutes: 20,
    defaultPriority: "high",
  },
  {
    id: "worship",
    nameAr: "عبادة",
    icon: "sparkles",
    color: "teal",
    defaultDurationMinutes: 25,
    defaultPriority: "high",
  },
  {
    id: "family",
    nameAr: "العائلة",
    icon: "home",
    color: "amber",
    defaultDurationMinutes: 45,
    defaultPriority: "medium",
  },
  {
    id: "health",
    nameAr: "الصحة",
    icon: "activity",
    color: "sky",
    defaultDurationMinutes: 45,
    defaultPriority: "medium",
  },
  {
    id: "study",
    nameAr: "تعلم",
    icon: "book",
    color: "violet",
    defaultDurationMinutes: 50,
    defaultPriority: "medium",
  },
]

export const seedTimeBlocks: TimeBlock[] = [
  {
    id: "last_sixth_to_fajr",
    nameAr: "السدس / قبل الفجر",
    sortOrder: 10,
    color: "indigo",
    startSource: "fixed",
    fixedStart: "03:20",
    endSource: "Fajr",
  },
  {
    id: "fajr_to_sunrise",
    nameAr: "الفجر إلى الشروق",
    sortOrder: 20,
    color: "emerald",
    startSource: "Fajr",
    endSource: "Sunrise",
  },
  {
    id: "sunrise_to_dhuhr",
    nameAr: "الشروق إلى الظهر",
    sortOrder: 30,
    color: "sky",
    startSource: "Sunrise",
    endSource: "Dhuhr",
  },
  {
    id: "dhuhr_to_asr",
    nameAr: "الظهر إلى العصر",
    sortOrder: 40,
    color: "amber",
    startSource: "Dhuhr",
    endSource: "Asr",
  },
  {
    id: "asr_to_maghrib",
    nameAr: "العصر إلى المغرب",
    sortOrder: 50,
    color: "orange",
    startSource: "Asr",
    endSource: "Maghrib",
  },
  {
    id: "maghrib_to_isha",
    nameAr: "المغرب إلى العشاء",
    sortOrder: 60,
    color: "rose",
    startSource: "Maghrib",
    endSource: "Isha",
  },
  {
    id: "isha_to_sleep",
    nameAr: "العشاء إلى النوم / السدس",
    sortOrder: 70,
    color: "slate",
    startSource: "Isha",
    endSource: "fixed",
    fixedEnd: "23:30",
  },
]

const routineStartDate = "2026-05-24"

function taskTemplate(
  template: Omit<
    TaskTemplate,
    "repeatInterval" | "startDate" | "endDate" | "isActive"
  >
): TaskTemplate {
  return {
    ...template,
    repeatInterval: 1,
    startDate: routineStartDate,
    isActive: true,
  }
}

export const seedTaskTemplates: TaskTemplate[] = [
  taskTemplate({
    id: "before-fajr",
    title: "قيام",
    categoryId: "worship",
    defaultTimeBlockId: "last_sixth_to_fajr",
    defaultDurationMinutes: 5,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: ["حزب قيام", "دعاء شامل", "استخارة", "توبة"],
    color: "indigo",
    includeInCalendar: true,
    sortOrder: 10,
  }),
  taskTemplate({
    id: "suhoor-istighfar",
    title: "سحور+استغفار",
    categoryId: "worship",
    defaultTimeBlockId: "last_sixth_to_fajr",
    defaultDurationMinutes: 20,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: ["استغفار"],
    color: "teal",
    includeInCalendar: true,
    sortOrder: 20,
  }),
  taskTemplate({
    id: "prepare-istighfar",
    title: "إعداد+استغفار",
    categoryId: "worship",
    defaultTimeBlockId: "last_sixth_to_fajr",
    defaultDurationMinutes: 12,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: ["استغفار"],
    color: "teal",
    includeInCalendar: true,
    sortOrder: 30,
  }),
  taskTemplate({
    id: "development",
    title: "تطوير",
    categoryId: "study",
    defaultTimeBlockId: "last_sixth_to_fajr",
    defaultDurationMinutes: 15,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "violet",
    includeInCalendar: true,
    sortOrder: 40,
  }),
  taskTemplate({
    id: "fajr",
    title: "صلاة الفجر",
    categoryId: "prayer",
    defaultTimeBlockId: "fajr_to_sunrise",
    defaultDurationMinutes: 20,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    notes: "قبل الصلاة وبعدها",
    checklist: ["ترديد الأذان", "أذكار الصلاة", "أذكار الصباح"],
    color: "emerald",
    includeInCalendar: true,
    sortOrder: 10,
  }),
  taskTemplate({
    id: "exercise",
    title: "رياضة",
    categoryId: "health",
    defaultTimeBlockId: "fajr_to_sunrise",
    defaultDurationMinutes: 35,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: ["مقاومة / جري"],
    color: "sky",
    includeInCalendar: true,
    sortOrder: 20,
  }),
  taskTemplate({
    id: "english",
    title: "انجليزي",
    categoryId: "study",
    defaultTimeBlockId: "fajr_to_sunrise",
    defaultDurationMinutes: 30,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "violet",
    includeInCalendar: true,
    sortOrder: 30,
  }),
  taskTemplate({
    id: "morning-sleep",
    title: "نوم",
    categoryId: "health",
    defaultTimeBlockId: "sunrise_to_dhuhr",
    defaultDurationMinutes: 90,
    defaultPriority: "low",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "slate",
    includeInCalendar: true,
    sortOrder: 40,
  }),
  taskTemplate({
    id: "family-breakfast",
    title: "فطور مع الأسرة",
    categoryId: "family",
    defaultTimeBlockId: "sunrise_to_dhuhr",
    defaultDurationMinutes: 45,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "amber",
    includeInCalendar: true,
    sortOrder: 50,
  }),
  taskTemplate({
    id: "dhuhr",
    title: "صلاة الظهر",
    categoryId: "prayer",
    defaultTimeBlockId: "dhuhr_to_asr",
    defaultDurationMinutes: 20,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: ["ترديد الأذان", "أذكار الصلاة"],
    color: "amber",
    includeInCalendar: true,
    sortOrder: 10,
  }),
  taskTemplate({
    id: "family-lunch",
    title: "غداء مع العائلة",
    categoryId: "family",
    defaultTimeBlockId: "dhuhr_to_asr",
    defaultDurationMinutes: 60,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "amber",
    includeInCalendar: true,
    sortOrder: 20,
  }),
  taskTemplate({
    id: "asr",
    title: "صلاة العصر",
    categoryId: "prayer",
    defaultTimeBlockId: "asr_to_maghrib",
    defaultDurationMinutes: 20,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: ["ترديد الأذان", "أذكار الصلاة"],
    color: "orange",
    includeInCalendar: true,
    sortOrder: 10,
  }),
  taskTemplate({
    id: "family-core",
    title: "الأسرة",
    categoryId: "family",
    defaultTimeBlockId: "asr_to_maghrib",
    defaultDurationMinutes: 30,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "amber",
    includeInCalendar: true,
    sortOrder: 20,
  }),
  taskTemplate({
    id: "extended-family",
    title: "العائلة",
    categoryId: "family",
    defaultTimeBlockId: "asr_to_maghrib",
    defaultDurationMinutes: 30,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "amber",
    includeInCalendar: true,
    sortOrder: 30,
  }),
  taskTemplate({
    id: "last-hour",
    title: "آخر ساعة",
    categoryId: "worship",
    defaultTimeBlockId: "asr_to_maghrib",
    defaultDurationMinutes: 60,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    notes: "آخر ساعة قبل المغرب",
    checklist: [],
    color: "orange",
    includeInCalendar: true,
    sortOrder: 40,
  }),
  taskTemplate({
    id: "maghrib",
    title: "صلاة المغرب",
    categoryId: "prayer",
    defaultTimeBlockId: "maghrib_to_isha",
    defaultDurationMinutes: 20,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: ["ترديد الأذان", "أذكار الصلاة", "أذكار المساء"],
    color: "rose",
    includeInCalendar: true,
    sortOrder: 10,
  }),
  taskTemplate({
    id: "arabic",
    title: "عربي",
    categoryId: "study",
    defaultTimeBlockId: "maghrib_to_isha",
    defaultDurationMinutes: 40,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "violet",
    includeInCalendar: true,
    sortOrder: 20,
  }),
  taskTemplate({
    id: "play",
    title: "لعب",
    categoryId: "family",
    defaultTimeBlockId: "maghrib_to_isha",
    defaultDurationMinutes: 30,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "amber",
    includeInCalendar: true,
    sortOrder: 30,
  }),
  taskTemplate({
    id: "isha",
    title: "صلاة العشاء",
    categoryId: "prayer",
    defaultTimeBlockId: "isha_to_sleep",
    defaultDurationMinutes: 20,
    defaultPriority: "high",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: ["ترديد الأذان", "أذكار الصلاة"],
    color: "slate",
    includeInCalendar: true,
    sortOrder: 10,
  }),
  taskTemplate({
    id: "family-dinner",
    title: "عشاء مع العائلة",
    categoryId: "family",
    defaultTimeBlockId: "isha_to_sleep",
    defaultDurationMinutes: 45,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "amber",
    includeInCalendar: true,
    sortOrder: 20,
  }),
  taskTemplate({
    id: "friends-family-first",
    title: "الأصدقاء + الأسرة + العائلة",
    categoryId: "family",
    defaultTimeBlockId: "isha_to_sleep",
    defaultDurationMinutes: 35,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "amber",
    includeInCalendar: true,
    sortOrder: 30,
  }),
  taskTemplate({
    id: "friends-family-second",
    title: "الأصدقاء + الأسرة + العائلة",
    categoryId: "family",
    defaultTimeBlockId: "isha_to_sleep",
    defaultDurationMinutes: 35,
    defaultPriority: "medium",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "amber",
    includeInCalendar: true,
    sortOrder: 40,
  }),
  taskTemplate({
    id: "night-sleep",
    title: "نوم",
    categoryId: "health",
    defaultTimeBlockId: "isha_to_sleep",
    defaultDurationMinutes: 45,
    defaultPriority: "low",
    repeatType: "daily",
    repeatDays: [],
    notes: "",
    checklist: [],
    color: "slate",
    includeInCalendar: true,
    sortOrder: 50,
  }),
]

export const seedPrayerDays: PrayerDay[] = [
  "2026-05-24",
  "2026-05-25",
  "2026-05-26",
  "2026-05-27",
  "2026-05-28",
  "2026-05-29",
  "2026-05-30",
].map((date, index) => ({
  date,
  timezone: "Asia/Riyadh",
  timings: {
    Fajr: `04:${String(12 + index).padStart(2, "0")}`,
    Sunrise: `05:${String(37 + index).padStart(2, "0")}`,
    Dhuhr: "11:54",
    Asr: "15:15",
    Maghrib: "18:38",
    Isha: "20:08",
  },
}))
